<?php 
/**
	Admin Page Framework v3.8.12 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/collapsing.category-list>
	Copyright (c) 2013-2016, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class collapsingCategoryList_AdminPageFramework_Form_View___CSS_term_meta extends collapsingCategoryList_AdminPageFramework_Form_View___CSS_Base {
    protected function _get() {
        return $this->_getRules();
    }
    private function _getRules() {
        return ".collapsing.category-list-form-table-outer-row-term_meta,.collapsing.category-list-form-table-outer-row-term_meta > td {margin: 0;padding: 0;}.collapsing.category-list-form-table-term_meta > tbody > tr > td {margin-left: 0;padding-left: 0;}.collapsing.category-list-form-table-term_meta .collapsing.category-list-sectionset,.collapsing.category-list-form-table-term_meta .collapsing.category-list-section {margin-bottom: 0;}.collapsing.category-list-form-table-term_meta.add-new-term .title-colon {margin-left: 0.2em;}.collapsing.category-list-form-table-term_meta.add-new-term .collapsing.category-list-section .form-table > tbody > tr > td,.collapsing.category-list-form-table-term_meta.add-new-term .collapsing.category-list-section .form-table > tbody > tr > th{display: inline-block;width: 100%;padding: 0;float: right;clear: right;}.collapsing.category-list-form-table-term_meta.add-new-term .collapsing.category-list-field {width: auto;}.collapsing.category-list-form-table-term_meta.add-new-term .collapsing.category-list-field {max-width: 100%;}.collapsing.category-list-form-table-term_meta.add-new-term .sortable .collapsing.category-list-field {width: auto;} .collapsing.category-list-form-table-term_meta.add-new-term .collapsing.category-list-section .form-table > tbody > tr > th {font-size: 13px;line-height: 1.5;margin: 0;font-weight: 700;}.collapsing.category-list-form-table-term_meta .collapsing.category-list-section-title h3 {border: none;font-weight: bold;font-size: 1.12em;margin: 0;padding: 0;font-family: 'Open Sans', sans-serif; cursor: inherit; -webkit-user-select: inherit;-moz-user-select: inherit;user-select: inherit;}.collapsing.category-list-form-table-term_meta .collapsing.category-list-collapsible-title h3 {margin: 0;}.collapsing.category-list-form-table-term_meta h4 {margin: 1em 0;font-size: 1.04em;}.collapsing.category-list-form-table-term_meta .collapsing.category-list-section-tab h4 {margin: 0;} ";
    }
}
