<?php 
/**
	Admin Page Framework v3.8.12 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/collapsing.category-list>
	Copyright (c) 2013-2016, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class collapsingCategoryList_AdminPageFramework_Form_View___Script_OptionStorage extends collapsingCategoryList_AdminPageFramework_Form_View___Script_Base {
    static public function getScript() {
        return <<<JAVASCRIPTS
(function ( $ ) {
            
    $.fn.acollapsingCategoryList_AdminPageFrameworkInputOptions = {}; 
                            
    $.fn.storecollapsingCategoryList_AdminPageFrameworkInputOptions = function( sID, vOptions ) {
        var sID = sID.replace( /__\d+_/, '___' );	// remove the section index. The g modifier is not used so it will replace only the first occurrence.
        $.fn.acollapsingCategoryList_AdminPageFrameworkInputOptions[ sID ] = vOptions;
    };	
    $.fn.getcollapsingCategoryList_AdminPageFrameworkInputOptions = function( sID ) {
        var sID = sID.replace( /__\d+_/, '___' ); // remove the section index
        return ( 'undefined' === typeof $.fn.acollapsingCategoryList_AdminPageFrameworkInputOptions[ sID ] )
            ? null
            : $.fn.acollapsingCategoryList_AdminPageFrameworkInputOptions[ sID ];
    }

}( jQuery ));
JAVASCRIPTS;
        
    }
}
