<?php 
/**
	Admin Page Framework v3.8.12 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/collapsing.category-list>
	Copyright (c) 2013-2016, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class collapsingCategoryList_AdminPageFramework_Form_View___Attribute_SectionTableBody extends collapsingCategoryList_AdminPageFramework_Form_View___Attribute_Base {
    public $sContext = 'section_table_content';
    protected function _getAttributes() {
        $_sCollapsibleType = $this->getElement($this->aArguments, array('collapsible', 'type'), 'box');
        return array('class' => $this->getAOrB($this->aArguments['_is_collapsible'], 'collapsing.category-list-collapsible-section-content' . ' ' . 'collapsing.category-list-collapsible-content' . ' ' . 'accordion-section-content' . ' ' . 'collapsing.category-list-collapsible-content-type-' . $_sCollapsibleType, null),);
    }
}
